CREATE TABLE IF NOT EXISTS events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  date       DATE NOT NULL,
  description VARCHAR(200),
  end_time   TIME(6) NOT NULL,
  name       VARCHAR(20) NOT NULL,
  start_time TIME(6) NOT NULL,
  owner_id   BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS grop_events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  date       DATE,
  description VARCHAR(200),
  end_time   TIME(6),
  name       VARCHAR(30) NOT NULL,
  start_time TIME(6),
  status     VARCHAR(255) CHECK (status IN ('PENDING','CONFIRMED')),
  owner_id   BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_group_events (
  group_event_id BIGINT NOT NULL,
  user_id        BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name     VARCHAR(20) NOT NULL,
  surname  VARCHAR(30) NOT NULL,
  username VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS events
  ADD CONSTRAINT event_owner_fk
  FOREIGN KEY (owner_id) REFERENCES users;

ALTER TABLE IF EXISTS grop_events
  ADD CONSTRAINT grop_events_owner_fk
  FOREIGN KEY (owner_id) REFERENCES users;

ALTER TABLE IF EXISTS user_group_events
  ADD CONSTRAINT user_group_events_user_fk
  FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE IF EXISTS user_group_events
  ADD CONSTRAINT user_group_events_group_event_fk
  FOREIGN KEY (group_event_id) REFERENCES grop_events;
